server:
  id: 1
  type: test

spring:
  config.activate.on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/momagent
    username: momagent
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
      auto_quote_keyword: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: debug
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

jwt:
  secret: AGVeqC3DaElzFlY3JKdEtlYLJldEtMNOeBNlY3JldEtleQ==

crypto:
  secret-key: 12345678901234567890123456789012
  init-vector: agentTest1234567
